# Generated by Django 3.2.2 on 2021-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default='1998-06-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.CharField(default='rcb', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.CharField(default='1am', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='chennai', max_length=250),
            preserve_default=False,
        ),
    ]
