# Generated by Django 3.2.2 on 2021-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210510_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(default='eew', max_length=200),
            preserve_default=False,
        ),
    ]
