# Generated by Django 3.2.2 on 2021-05-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_match_icon1'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='icon2',
            field=models.ImageField(default='ddd', upload_to=''),
            preserve_default=False,
        ),
    ]
